FROM mambaorg/micromamba:1.5.10-noble AS build-env

ENV PYTHONDONTWRITEBYTECODE=1
USER root

# make sure the install below is not cached by docker
ADD https://loripsum.net/api /opt/docker/etc/gibberish-to-bust-docker-image-cache

COPY conda-lock.yml /tmp/conda-lock.yml

RUN echo "**** install base env ****" && \
    micromamba create --yes --quiet --name cf-feedstock-ops --file /tmp/conda-lock.yml
RUN echo "**** cleanup ****" && \
    micromamba clean --all --force-pkgs-dirs --yes && \
    find "${MAMBA_ROOT_PREFIX}" -follow -type f \( -iname '*.a' -o -iname '*.pyc' -o -iname '*.js.map' \) -delete
RUN echo "**** finalize ****" && \
    mkdir -p "${MAMBA_ROOT_PREFIX}/locks" && \
    chmod 777 "${MAMBA_ROOT_PREFIX}/locks"

FROM frolvlad/alpine-glibc:alpine-3.16_glibc-2.34
LABEL maintainer="conda-forge <conda-forge@googlegroups.com>"

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV TMPDIR=/tmp
ENV CF_FEEDSTOCK_OPS_DIR=/opt/cf-feedstock-ops
ENV CF_FEEDSTOCK_OPS_ENV=cf-feedstock-ops

RUN apk add --no-cache bash

COPY --from=build-env /opt/conda /opt/conda
COPY --from=build-env /usr/bin/micromamba /usr/bin/micromamba

# use bash for a while to make conda manipulations easier
SHELL ["/bin/bash", "-l", "-c"]

# Lucky group gets permission to write in the conda dir
RUN addgroup -g 32766 lucky && \
    chown -R root /opt/conda && \
    chgrp -R lucky /opt/conda && chmod -R g=u /opt/conda

# deal with entrypoint
COPY entrypoint_wda /opt/docker/bin/entrypoint
RUN chmod +x /opt/docker/bin/entrypoint

# not needed right now but keeping just in case
# now install the main code
# COPY . $CF_FEEDSTOCK_OPS_DIR
# RUN micromamba activate $CF_FEEDSTOCK_OPS_ENV && \
#     cd $CF_FEEDSTOCK_OPS_DIR && \
#     pip install --no-deps --no-build-isolation -e . && \
#     cd -

# now make the conda user for running tasks and set the user
RUN adduser --disabled-password --shell /bin/bash conda
ENV HOME=/home/conda
ENV USER=conda
ENV LOGNAME=conda
ENV MAIL=/var/spool/mail/conda
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin
RUN chown conda:conda $HOME && \
    # cp -R /etc/skel $HOME && \
    # chown -R conda:conda $HOME/skel && \
    # (ls -A1 $HOME/skel | xargs -I {} mv -n $HOME/skel/{} $HOME) && \
    # rm -Rf $HOME/skel && \
    cd $HOME
USER conda

# deal with git config for user and mounted directory
RUN micromamba shell init -r /opt/conda -s bash && \
    micromamba activate $CF_FEEDSTOCK_OPS_ENV && \
    git config --global --add safe.directory /cf_feedstock_ops_dir && \
    git config --global init.defaultBranch main && \
    git config --global user.email "conda@conda.conda" && \
    git config --global user.name "conda conda"

# put the shell back
SHELL ["/bin/sh", "-c"]

ENTRYPOINT [ "/opt/conda/bin/tini", "--", "/opt/docker/bin/entrypoint" ]
CMD [ "/bin/bash" ]
