#!/usr/bin/env bash

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

source /opt/conda/etc/profile.d/conda.sh

conda activate base

conda info


mkdir -p ${HOME}/.conda-smithy

echo ${GH_TOKEN} > ${HOME}/.conda-smithy/github.token
echo ${CIRCLE_TOKEN} > ${HOME}/.conda-smithy/circle.token

git config --global user.name "conda-forge-admin"
git config --global user.email "pelson.pub+conda-forge@gmail.com"

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

$@
