#!/usr/bin/env bash

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

source /opt/conda/etc/profile.d/conda.sh

conda activate base

conda info


mkdir -p ${HOME}/.conda-smithy

echo ${GH_TOKEN} > ${HOME}/.conda-smithy/github.token
echo ${STAGING_BINSTAR_TOKEN} > ${HOME}/.conda-smithy/anaconda.token

git config --global user.name "conda-forge-webservices[bot]"
git config --global user.email "121827174+conda-forge-webservices[bot]@users.noreply.github.com"

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

$@
