#!/usr/bin/env bash

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

source /opt/conda/etc/profile.d/conda.sh

conda activate base

conda info


mkdir -p ${HOME}/.conda-smithy

echo ${GH_TOKEN} > ${HOME}/.conda-smithy/github.token
echo ${CIRCLE_TOKEN} > ${HOME}/.conda-smithy/circle.token
echo ${TRAVIS_TOKEN} > ${HOME}/.conda-smithy/travis.token
echo ${AZURE_TOKEN} > ${HOME}/.conda-smithy/azure.token
echo ${DRONE_TOKEN} > ${HOME}/.conda-smithy/drone.token
echo ${STAGING_BINSTAR_TOKEN} > ${HOME}/.conda-smithy/anaconda.token

git config --global user.name "conda-forge-admin"
git config --global user.email "pelson.pub+conda-forge@gmail.com"

export DEBUG_FEEDSTOCK_TOKENS=1

git clone https://${GH_TOKEN}@github.com/conda-forge/feedstock-outputs.git
pushd feedstock-outputs
git remote set-url --push origin https://${GH_TOKEN}@github.com/conda-forge/feedstock-outputs.git
popd
export FEEDSTOCK_OUTPUTS_REPO=`pwd`/feedstock-outputs

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

$@
